name: sd
channels:
  - defaults
  # - pytorch
  - conda-forge
dependencies:
  - conda-forge::facexlib
  - conda-forge::ncurses # fixes: libtinfo.so.6: no version information available (required by bash)
  # - cudatoolkit=11.3
  # - numpy
  - python<=3.11
  # - pytorch
  - pip
  # - pip:
    # - accelerate
    # - albumentations==0.4.3
    # - astunparse
    # - basicsr
    # - blendmodes
    # - clean-fid
    # - einops
    # - fairscale==0.4.4
    # - fastapi==0.90.1
    # - font-roboto
    # - fonts
    # - gfpgan
    # - GitPython
    # - gradio==3.31.0
    # - imageio-ffmpeg==0.4.2
    # - imageio==2.9.0
    # - inflection
    # - invisible-watermark>=0.1.5
    # - jsonmerge
    # - kornia
    # - lark
    # - numpy
    # - omegaconf
    # - open-clip-torch==2.7.0
    # - openai-clip
    # - opencv-contrib-python
    # - opencv-python
    # - picklescan
    # - piexif
    # - Pillow
    # - psutil
    # - pudb==2019.2
    # - pytorch_lightning==1.7.7
    # - realesrgan
    # - requests
    # - resize-right
    # - rich
    # - safetensors
    # - scikit-image>=0.19
    # - streamlit-drawable-canvas==0.8.0
    # - streamlit>=0.73.1
    # - test-tube>=0.7.5
    # - timm==0.4.12
    # - tomesd
    # - torch
    # - torchdiffeq
    # - torchmetrics
    # - torchsde
    # - torchvision #==0.13.1
    # - transformers==4.25.1
    # - webdataset==0.2.5