name: sd
channels:
  - defaults
  - conda-forge
dependencies:
  # - conda-forge::facexlib
  - conda-forge::ncurses # fixes: libtinfo.so.6: no version information available (required by bash)
  - python<=3.10
  - pip
  - pip:
    - picklescan